### PR TITLE
Improve country - parameter list

### PR DESCRIPTION
**Pull request by niklaslong**
Not all parameters are available for all countries - this PR implements the precise list of parameters available for each country

### CODE REVIEW

**Comment by marcoow** [comment]
What problem does this solve?

**Comment by niklaslong** [comment]
@marcoow the first implementation of the download for European data only included 4 of the six available parameters for each country (see #191). In this PR I added the corrected the list so that we're downloading all available data.

**Comment by marcoow** [comment]
The problem with this is we now have to maintain this relatively big matrix and if another value for any country is added we would have to add it to this matrix before we would actually use it. Can we just try and get all values for all countries anyway and then see which of the values are actually present in the data? Ideally we could do the same thing for countries and somehow find out for which countries data is available vs. listing all individual countries here…

**Comment by niklaslong** [comment]
I see your point although I don't really see how we could do that 🤔 
We're programmatically constructing the URL from which the CSV file is being downloaded. Countries shouldn't change very often (unless Europe breaks apart dramatically). 

We could fire off requests and in the event of a failure just move to the next. In any case we'd need to hardcode the list of countries and at the very least the 6 available parameters. 

I'll do some some research: we're essentially downloading data from a file directory so maybe we could query the top level and retrieve the list in that way.

**Comment by niklaslong** [comment]
Actually, that last option seems like it could work - I'll give the implementation a try.

**Comment by marcoow** [comment]
You can actually download the list of available URLs (data) here: http://discomap.eea.europa.eu/map/fme/latest/files.txt

**Pull request merged**
