### PR TITLE
shift DateTime back two hours in factories

### PR DESCRIPTION
**Pull request by niklaslong**
follow up to #120

### CODE REVIEW

**Comment by niklaslong** [comment]
@marcoow I've added the `datetime` to the `insert` calls on the `open_aq` tests. I haven't specified the `datetime` and left the default factory in the controller tests as the time isn't what's being tested (it just needs to have a value as we're using `assert json_response` and that means we can't just "ignore" some values). I think we should consider refactoring some of these tests after changing AQ providers (we'll probably have to anyway).

**Comment by niklaslong** [comment]
@marcoow I've added the `datetime` to the `insert` calls on the `open_aq` tests. I haven't specified the `datetime` and left the default factory in the controller tests as the time isn't what's being tested (it just needs to have a value as we're using `assert json_response` and that means we can't just "ignore" some values). I think we should consider refactoring some of these tests after changing AQ providers (we'll probably have to anyway).

**Comment by niklaslong** [comment]
@marcoow 🤦‍♂️ I forgot the minus sign - point was to shift them *back* two hours...
The only case when the time is actually important is in the data tests (to make sure we only return recent measurements from the DB). In those cases we're already passing in the time to the factory, which is why I was confused as to why you didn't want to use the factory defaults in the cases of this PR?

**Comment by marcoow** [comment]
We can use the defaults in all cases where we don't care about the exact times. Only if we assert on the times that we're writing, we should set these times in the test itself so the test doesn't rely on anything that's set in the factory. So does that mean this PR isn't needed at all then?

**Comment by niklaslong** [comment]
@marcoow No I don't think we need it, unless we still want to shift back the factory defaults by two hours so that it's more representative of the real data?

**Comment by marcoow** [comment]
I think it's fine as it is 👍

**Pull request closed without merging**
