### PR TITLE
replace OpenAQ with EEA

### PR DESCRIPTION
**Pull request by niklaslong**
based on discussions in #200 and #104 

todo:
- [x] remove OpenAQ
- [x] translate `search_term` to `lat, lon` to search db using Google
- [x] asynchronously refresh data from EEA
- [x] tests
- [x] update README

note: Heroku scheduler will need to be updated, database reset might also be a good idea

### CODE REVIEW

**Comment by niklaslong** [comment]
Currently we're doing a pattern match on the `search_term` in the DB (which is why the search was so slow). I'll be looking into optimizing the search next.
I removed Google because we're not actually using it anywhere for the moment.

**Comment by marcoow** [comment]
Ugh, no – we cannot search for locations directly in the DB. If I do not enter the street name we have in the DB then, I won't find anything even if we have data for the next street that might just be 50m away. That's why we need to use Google to translate the address to coordinates and then search in the DB with these coordinates.

**Comment by niklaslong** [comment]
We're currently returning any location which partially matches the `search_term` either in the `city` or the `identifier` fields. I was thinking of implementing a (faster) full text search and perhaps improving the `identifier` when initially storing the data with Google? 
Wouldn't querying Google for each query make the whole app really slow and defeat the whole purpose?

**Comment by marcoow** [comment]
So we always need to look up the data in the DB based on lat/lon – we cannot build our own text based location search for the reason I explained above. Always looking up data via lat/lon should also be what we're doing now.

**Comment by marcoow** [comment]
Ugh, I just realize this was changed – https://github.com/simplabs/breethe-server/blob/master/apps/breethe/lib/breethe/data/location.ex#L46. We need to fix that – with this implementation we'll have relative poor quality responses in many/most cases.

**Comment by niklaslong** [comment]
Sounds good, I'll make the changes.

**Comment by niklaslong** [comment]
@marcoow this should be all set now

**Pull request merged**
